update submission.md
rishabkumar7/cloud-resume-api pull request #28
Opened 2024-07-25 22:40 UTC by Anandhakrishnan27

2024-07-26 15:36 UTC, rishabkumar7 requested changes

2024-07-26 15:36 UTC, rishabkumar7 commented on docs/submissions.md
> +|Anandha krishnan|https://jner4mrs02.execute-api.us-east-1.amazonaws.com/prod|https://github.com/Anandhakrishnan27/resumeApi
Can you include the closing pipe | at the end of the record.

2024-07-26 15:36 UTC, rishabkumar7 commented on README.md
This is added automatically by the GitHub Action, can you revert this commit.

2024-07-26 16:52 UTC, Anandhakrishnan27 commented on README.md
i reverted the commit

2024-07-26 16:52 UTC, Anandhakrishnan27 commented on docs/submissions.md
> +|Anandha krishnan|https://jner4mrs02.execute-api.us-east-1.amazonaws.com/prod|https://github.com/Anandhakrishnan27/resumeApi
i have included the pipe at the end

2024-07-26 17:58 UTC, rishabkumar7 approved these changes
LGTM, thank you.

2024-07-26 17:58 UTC, merged

2024-09-03 16:23 UTC, rishabkumar7 commented
Hi @Anandhakrishnan27 congrats on winning the AWS Credits, could you share your preferred social media so that I can share the details. Thank you.

2024-09-03 16:30 UTC, Anandhakrishnan27 commented
You can share it via my LinkedIn and my profile is
https://www.linkedin.com/in/anandhakrishnan27?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

On Tue, Sep 3, 2024, 9:24 AM Rishab Kumar ***@***.***> wrote:

> Hi @Anandhakrishnan27 <https://github.com/Anandhakrishnan27> congrats on
> winning the AWS Credits, could you share your preferred social media so
> that I can share the details. Thank you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rishabkumar7/cloud-resume-api/pull/28#issuecomment-2326945023>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANBSL2NUIOFUGFEOC4SWPIDZUXPC5AVCNFSM6AAAAABLPNVDC6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRWHE2DKMBSGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>